Frontend:
  Translation:
    impl: NoTranslation
    max_addr: 18446744073709551616
  clock_ratio: 1
  impl: ReadWriteTrace
  num_expected_insts: 1000000
  path: /home/fann/projects/cache_simulator/sampled_trace/541_sampled.txt
MemorySystem:
  AddrMapper:
    impl: RoBaRaCoCh
  Controller:
    RefreshManager:
      impl: AllBank
    RowPolicy:
      cap: 4
      impl: OpenRowPolicy
    Scheduler:
      impl: FRFCFS
    impl: Generic
    plugins: null
  DRAM:
    RFM:
      BRC: 2
    impl: DDR5
    org:
      channel: 1
      preset: DDR5_32Gb_x4
      rank: 2
    timing:
      preset: DDR5_3200AN
  clock_ratio: 1
  impl: GenericDRAM
