Frontend:
  Translation:
    impl: NoTranslation
    max_addr: 18446744073709551616
  clock_ratio: 16
  impl: ReadWriteTrace
  num_expected_insts: 1000000
  path: /media/fann/T9/MEM_INTENSIVE_SPEC_GAP/tc_twitter_sampled.txt
MemorySystem:
  AddrMapper:
    impl: MOP4CLXOR
  Controller:
    RefreshManager:
      impl: AllBank
    RowPolicy:
      cap: 4
      impl: OpenRowPolicy
    Scheduler:
      impl: FRFCFS
    impl: Generic
    plugins: null
    wait_ratio: '2.286'
  DRAM:
    RFM:
      BRC: 2
    impl: DDR5
    org:
      channel: 1
      preset: DDR5_32Gb_x4
      rank: 2
    timing:
      preset: DDR5_6400AN
  clock_ratio: 1
  impl: GenericDRAM
